/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class AccountSettingView extends javax.swing.JPanel {

    /**
     * Creates new form AccountSettingView
     */
    public AccountSettingView() {
        initComponents();
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdate = btnUpdate;
    }

    public JComboBox<String> getCbxGender() {
        return cbxGender;
    }

    public void setCbxGender(JComboBox<String> cbxGender) {
        this.cbxGender = cbxGender;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public void setLblEmail(JLabel lblEmail) {
        this.lblEmail = lblEmail;
    }

    public JLabel getLblErrAddress() {
        return lblErrAddress;
    }

    public void setLblErrAddress(JLabel lblErrAddress) {
        this.lblErrAddress = lblErrAddress;
    }

    public JLabel getLblErrDateOfBirth() {
        return lblErrDateOfBirth;
    }

    public void setLblErrDateOfBirth(JLabel lblErrDateOfBirth) {
        this.lblErrDateOfBirth = lblErrDateOfBirth;
    }

    public JLabel getLblErrGender() {
        return lblErrGender;
    }

    public void setLblErrGender(JLabel lblErrGender) {
        this.lblErrGender = lblErrGender;
    }

    public JLabel getLblErrUserName() {
        return lblErrUserName;
    }

    public void setLblErrUserName(JLabel lblErrUserName) {
        this.lblErrUserName = lblErrUserName;
    }

    public JLabel getLblStartWorkingDate() {
        return lblStartWorkingDate;
    }

    public void setLblStartWorkingDate(JLabel lblStartWorkingDate) {
        this.lblStartWorkingDate = lblStartWorkingDate;
    }

    public JTextField getTxtAddress() {
        return txtAddress;
    }

    public void setTxtAddress(JTextField txtAddress) {
        this.txtAddress = txtAddress;
    }

    public JTextField getTxtDateOfBirth() {
        return txtDateOfBirth;
    }

    public void setTxtDateOfBirth(JTextField txtDateOfBirth) {
        this.txtDateOfBirth = txtDateOfBirth;
    }

    public JTextField getTxtUserName() {
        return txtUserName;
    }

    public void setTxtUserName(JTextField txtUserName) {
        this.txtUserName = txtUserName;
    }

    public JLabel getLblSuccess() {
        return lblSuccess;
    }

    public void setLblSuccess(JLabel lblSuccess) {
        this.lblSuccess = lblSuccess;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        cbxGender = new javax.swing.JComboBox<>();
        lblStartWorkingDate = new javax.swing.JLabel();
        lblErrUserName = new javax.swing.JLabel();
        lblErrAddress = new javax.swing.JLabel();
        lblErrGender = new javax.swing.JLabel();
        lblErrDateOfBirth = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblSuccess = new javax.swing.JLabel();

        jLabel1.setText("Email:");

        lblEmail.setText("jLabel2");

        jLabel3.setText("User Name:");

        jLabel4.setText("Address:");

        jLabel5.setText("Gender:");

        jLabel6.setText("Date Of Birth:");

        jLabel7.setText("Started Work Date:");

        txtUserName.setText("jTextField1");

        txtAddress.setText("jTextField1");

        txtDateOfBirth.setText("jTextField1");

        cbxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblStartWorkingDate.setText("jLabel2");

        lblErrUserName.setForeground(new java.awt.Color(255, 0, 0));
        lblErrUserName.setText("jLabel9");

        lblErrAddress.setForeground(new java.awt.Color(255, 0, 0));
        lblErrAddress.setText("jLabel9");

        lblErrGender.setForeground(new java.awt.Color(255, 0, 0));
        lblErrGender.setText("jLabel9");

        lblErrDateOfBirth.setForeground(new java.awt.Color(255, 0, 0));
        lblErrDateOfBirth.setText("jLabel9");

        btnUpdate.setText("Update");

        lblSuccess.setForeground(new java.awt.Color(0, 153, 0));
        lblSuccess.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrDateOfBirth)
                                    .addComponent(lblErrGender)
                                    .addComponent(lblErrAddress)
                                    .addComponent(lblErrUserName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblEmail))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(lblStartWorkingDate)
                            .addComponent(lblSuccess)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrDateOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblStartWorkingDate))
                .addGap(27, 27, 27)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(lblSuccess)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrAddress;
    private javax.swing.JLabel lblErrDateOfBirth;
    private javax.swing.JLabel lblErrGender;
    private javax.swing.JLabel lblErrUserName;
    private javax.swing.JLabel lblStartWorkingDate;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
