/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class SalaryReportView extends javax.swing.JPanel {

    /**
     * Creates new form SalaryReportView
     */
    public SalaryReportView() {
        initComponents();
    }

    public JButton getBtnCheckSalary() {
        return btnCheckSalary;
    }

    public void setBtnCheckSalary(JButton btnCheckSalary) {
        this.btnCheckSalary = btnCheckSalary;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblActualSalary() {
        return lblActualSalary;
    }

    public void setLblActualSalary(JLabel lblActualSalary) {
        this.lblActualSalary = lblActualSalary;
    }

    public JLabel getLblActualTimekeeping() {
        return lblActualTimekeeping;
    }

    public void setLblActualTimekeeping(JLabel lblActualTimekeeping) {
        this.lblActualTimekeeping = lblActualTimekeeping;
    }

    public JLabel getLblErrMessage() {
        return lblErrMessage;
    }

    public void setLblErrMessage(JLabel lblErrMessage) {
        this.lblErrMessage = lblErrMessage;
    }

    public JLabel getLblStandardSalary() {
        return lblStandardSalary;
    }

    public void setLblStandardSalary(JLabel lblStandardSalary) {
        this.lblStandardSalary = lblStandardSalary;
    }

    public JLabel getLblStandardTimekeeping() {
        return lblStandardTimekeeping;
    }

    public void setLblStandardTimekeeping(JLabel lblStandardTimekeeping) {
        this.lblStandardTimekeeping = lblStandardTimekeeping;
    }

    public JLabel getLblTime() {
        return lblTime;
    }

    public void setLblTime(JLabel lblTime) {
        this.lblTime = lblTime;
    }

    public JPanel getPnlSalaryReport() {
        return pnlSalaryReport;
    }

    public void setPnlSalaryReport(JPanel pnlSalaryReport) {
        this.pnlSalaryReport = pnlSalaryReport;
    }

    public JTable getTblTimekeeping() {
        return tblTimekeeping;
    }

    public void setTblTimekeeping(JTable tblTimekeeping) {
        this.tblTimekeeping = tblTimekeeping;
    }

    public JTextField getTxtMonth() {
        return txtMonth;
    }

    public void setTxtMonth(JTextField txtMonth) {
        this.txtMonth = txtMonth;
    }

    public JTextField getTxtYear() {
        return txtYear;
    }

    public void setTxtYear(JTextField txtYear) {
        this.txtYear = txtYear;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getLblMinuteLate() {
        return lblMinuteLate;
    }

    public void setLblMinuteLate(JLabel lblMinuteLate) {
        this.lblMinuteLate = lblMinuteLate;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCheckSalary = new javax.swing.JButton();
        pnlSalaryReport = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStandardTimekeeping = new javax.swing.JLabel();
        lblActualTimekeeping = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblStandardSalary = new javax.swing.JLabel();
        lblActualSalary = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMinuteLate = new javax.swing.JLabel();
        lblErrMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimekeeping = new javax.swing.JTable();

        jLabel1.setText("Month");

        jLabel2.setText("Year");

        btnCheckSalary.setText("View Salary");

        jLabel3.setText("Time:");

        jLabel4.setText("Standard Timekeeping:");

        jLabel5.setText("Actual Timekeeping:");

        lblStandardTimekeeping.setText("jLabel6");

        lblActualTimekeeping.setText("jLabel7");

        lblTime.setText("jLabel8");

        jLabel9.setText("Standard Salary:");

        jLabel10.setText("Actual Salary:");

        lblStandardSalary.setText("jLabel6");

        lblActualSalary.setText("jLabel7");

        jLabel11.setText("Minutes Late:");

        lblMinuteLate.setText("jLabel6");

        javax.swing.GroupLayout pnlSalaryReportLayout = new javax.swing.GroupLayout(pnlSalaryReport);
        pnlSalaryReport.setLayout(pnlSalaryReportLayout);
        pnlSalaryReportLayout.setHorizontalGroup(
            pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblActualTimekeeping))
                    .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStandardTimekeeping))
                    .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinuteLate)
                    .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblActualSalary))
                    .addComponent(lblStandardSalary))
                .addGap(137, 137, 137))
        );
        pnlSalaryReportLayout.setVerticalGroup(
            pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblTime))
                    .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(lblMinuteLate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalaryReportLayout.createSequentialGroup()
                        .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblStandardTimekeeping)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSalaryReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblActualTimekeeping)
                            .addComponent(jLabel10)))
                    .addGroup(pnlSalaryReportLayout.createSequentialGroup()
                        .addComponent(lblStandardSalary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblActualSalary)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblErrMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblErrMessage.setText("jLabel3");

        tblTimekeeping.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "In Time", "Out Time", "Come Late", "Leave Early"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTimekeeping);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSalaryReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckSalary)
                        .addGap(18, 18, 18)
                        .addComponent(lblErrMessage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckSalary)
                    .addComponent(lblErrMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSalaryReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActualSalary;
    private javax.swing.JLabel lblActualTimekeeping;
    private javax.swing.JLabel lblErrMessage;
    private javax.swing.JLabel lblMinuteLate;
    private javax.swing.JLabel lblStandardSalary;
    private javax.swing.JLabel lblStandardTimekeeping;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlSalaryReport;
    private javax.swing.JTable tblTimekeeping;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
